### ISSUE TITLE
Add a detailed description about what your app is doing

### ISSUE THREAD

**Issue by rakekniven** [g-artech/wrikesync#1]
Hello,

as a Wrike user I am curious about the features your app is offering.
The readme.md has content about installing/building the app.

Personally I am missing a description of the app.

Same for the Nextcloud App Store.

Thank you.

**Comment by arduino43** [comment]
+1

**Comment by rakekniven** [comment]
Has this app been abbandoned?

**Comment by arduino43** [comment]
Ya

**Comment by rakekniven** [comment]
Sad to here. Would you mind to add a comment to the app store page?
