### ISSUE TITLE
Please release the source code of the changes

### ISSUE THREAD

**Issue by aszlig** [g-artech/wrikesync#2]
The tags for version 1.0.1 through 1.1.2 all point to the same commit (bb73bade601fd6c5da161cfb99554da6fa8174cb). However the release tarballs contain changes that deviate from the source provided in this repository, some of them are generated/minified files.

Please either provide the changes here (by actually committing the changes and tagging them accordingly) or at least include the sources for the generated JS files in the tarball.

Thanks :-)

**Comment by aszlig** [comment]
@g-artech: And version 1.2.3 (the 7th version after 1.0.0) was released yesterday with no corresponding source code here and the tarball still contains generated files without the accompanying changes (nope, a JS source map doesn't count).

Cc: @blizz who merged the [certificate request](https://github.com/nextcloud/app-certificate-requests/pull/316).

**Comment by blizz** [comment]
@blizzz

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 30, 2020 at 4:35 PM, aszlig<notifications@github.com> wrote:   


@g-artech: And version 1.2.3 (the 7th version after 1.0.0) was released yesterday with no corresponding source code here and the tarball still contains generated files without the accompanying changes (nope, a JS source map doesn't count).

Cc: @blizz who merged the certificate request.

**Comment by g-artech** [comment]
> @g-artech: And version 1.2.3 (the 7th version after 1.0.0) was released yesterday with no corresponding source code here and the tarball still contains generated files without the accompanying changes (nope, a JS source map doesn't count).
> 
> 
> 
> Cc: @blizzz who merged the [certificate request](https://github.com/nextcloud/app-certificate-requests/pull/316).

Sorry for responding that late. We will provide the full source code at Monday.

**Comment by aszlig** [comment]
@blizz: Sorry, wrong "blizz" here, the right one was with 3 **z** instead of two, fixed accordingly.

@g-artech: Okay, thanks for the info.

**Comment by g-artech** [comment]
@aszlig The source code of the actual version v1.2.3 is now available in the master branch.

**Comment by aszlig** [comment]
@g-artech: Thanks, that was quick.

**Comment by g-artech** [comment]
> @g-artech: Thanks, that was quick.

If you have any other questions - just ask us. We will try to answer them faster than this time.

**Comment by aszlig** [comment]
@g-artech: Well, thanks, currently not really. I'm personally not even using your app, but since I do review/aggregation of the changes of *all* the Nextcloud apps published to the store, reviewing the changes becomes a major nuisance if the source code is not available (hence this issue). ;-)
